#!/usr/bin/env bash

PLUGIN="stillworking"
VERSION="1.1.0"
NODEJS="/Users/jeko/.nvm/versions/node/v12.14.0/bin/node"
ALACRITTY="/Applications/Alacritty.app/Contents/MacOS/alacritty"
TIMEOUT="$((10 * 60))"
SEPARATOR=";"

function workingdir() {
  LINK="$(readlink "$1")"
  if [ ! -z "$LINK" ]; then
    (cd "$(dirname "$1")"; workingdir "$LINK")
  else
    (cd "$(dirname "$1")"; pwd)
  fi
}

function indexjs() {
  "$ALACRITTY" -d 80 20 --working-directory "$WORKINGDIR" -e "$NODEJS" index.js
}

WORKINGDIR="$(workingdir "$0")"

ONCE=false
while [ ! -z "$1" ]; do
  if [ "$1" = "--once" ]; then
    ONCE=true
  fi
  shift
done

COMMAND=""
while [ "x$COMMAND" != "xq" ]; do
  indexjs
  VALUE="$(cat /tmp/stillworking-wakatime.out)"
  echo "$(date +%s)$SEPARATOR$VALUE" >> ~/.stillworking.db
  if [ ! -z "$VALUE" ]; then
    PROJECT="$(echo "$VALUE" | cut -d"$SEPARATOR" -f1)"
    ENTITY="$(echo "$VALUE" | cut -d"$SEPARATOR" -f2)"
    wakatime --write --plugin "$PLUGIN/$VERSION" --entity-type app --project "$PROJECT" --entity "$ENTITY" &
  fi
  if [ "$ONCE" = true ]; then
    exit 0
  fi
  echo '(r)efresh (q)uit'
  read -t "$TIMEOUT" COMMAND # every 14 minutes (wakatime timeout is 15 minutes)
done
